# Translated from the Ghostty faybtheme palette.
foreground #54fe50
background #1e181e
selection_foreground #ffffff
selection_background #56036b
cursor #fef93a
cursor_text_color #1e181e

color0 #211421
color1 #fc618d
color2 #10aa31
color3 #fd9353
color4 #f9db2d
color5 #5ad4e6
color6 #948ae3
color7 #c3c0b5
color8 #494949
color9 #ff0080
color10 #f2fe50
color11 #fef93a
color12 #8d81fe
color13 #fe61fa
color14 #57e6ff
color15 #ffffff
